### ISSUE TITLE
Add gemnasium to repositories index view

### ISSUE THREAD

**Issue by eefahy** [sul-dlss/quimby#22]
I don't think we need an additional field in the Repository model for this as we should be tracking all rails & gem repos for their gem dependencies. Gemnasium has an HTTP API and a cli to look into. http://docs.gemnasium.apiary.io/#introduction/api-versioning

**Comment by tallenaz** [comment]
For example:
```
% curl -X GET -u X:API_KEY https://api.gemnasium.com/v1/projects/sul-dlss/workflow-archiver
{"slug":"sul-dlss/workflow-archiver","name":"workflow-archiver","description":"","origin":"github","private":false,"color":"green","monitored":true,"unmonitored_reason":"","commit_sha":"ccb112118a2876c57a380f4e206b8b3017d4fa00"
```
