### ISSUE TITLE
investigate using names name for ids in urls

### ISSUE THREAD

**Issue by tallenaz** [sul-dlss/quimby#23]
so that we have `/repository/dor-services`, instead of, say, `/repository/1`

**Comment by tallenaz** [comment]
https://gist.github.com/jcasimir/1209730

**Comment by tallenaz** [comment]
something like:

repositories/searchworks/servers                                                
  dev: sw-webapp-dev-a                                                          
  prod: sw-webapp-prod-b

**Comment by eefahy** [comment]
closed by https://github.com/sul-dlss/quimby/pull/35
