### ISSUE TITLE
configure shibboleth auth for quimby

### ISSUE THREAD

**Issue by tallenaz** [sul-dlss/quimby#39]
https://uit.stanford.edu/service/shibboleth/sp

**Comment by tallenaz** [comment]
https://github.com/apokalipto/devise_saml_authenticatable

**Comment by jonrober** [comment]
I'll do a simple setup as talked about Friday, where the entirety of quimby-stage is just behind shibboleth.

**Comment by jonrober** [comment]
PR 73 closed the code part of this, and shib is set up on sul-quimby-stage.  The new code isn't yet pushed out.

**Comment by jonrober** [comment]
Closing the issue, code will be updated on stage at next general update there.
