### ISSUE TITLE
Add `whenever --upconfig` on cap deploys

### ISSUE THREAD

**Issue by eefahy** [sul-dlss/quimby#59]
That will create an entry in the quimby user crontab to run the `load_data:all` rake task every 2 hours

**Comment by eefahy** [comment]
Blocked by https://github.com/sul-dlss/quimby/issues/61

**Comment by jonrober** [comment]
Added to Capfile:
require 'whenever/capistrano'

Tested by pushing out to a server, and the cron job was created.

**Comment by tallenaz** [comment]
Fixed by da0189b
