### ISSUE TITLE
Create ServerPuppetdbData class

### ISSUE THREAD

**Issue by eefahy** [sul-dlss/quimby#60]
- [ ] create a `.run` instance method to load_data
- [ ] `create_or_find_by` the Server object based on the `fqdn`
  - [ ] load hostname
  - [ ] load ip
  - [ ] load / create fields for other attributes

**Comment by tallenaz** [comment]
with the puppetdb gem, this gets everything with `role::basenode`, need to figure out how to transform it into a list of certnames: 
```
p.request('resources', ['and', ['=', 'type', 'Class'], ['=', 'title', 'Role::Basenode']])
```
