### ISSUE TITLE
Update load_data:all rake task

### ISSUE THREAD

**Issue by eefahy** [sul-dlss/quimby#61]
Right now there's a implicit ordering to the load_data classes:
 - load Servers
 - load Repositories
 - load Deploy data

We should be more explicit in this ordering in the rake task

**Comment by eefahy** [comment]
Blocked by: https://github.com/sul-dlss/quimby/issues/60

**Comment by cmh2166** [comment]
What is the goal of the explicit-ness - add some dependencies to rake tasks? make sure each task can still be run atomically despite dependencies?

**Comment by tallenaz** [comment]
I'd say it's to add dependencies to the tasks - for example, the Servers need to be created first so that when the RepoData task gets to defining its DeployEnvironments, it can find the Servers it needs for them.

**Comment by cmh2166** [comment]
okay. will make a pass at this smaller task before meetings queue up tomorrow, then, if that's cool.

**Comment by cmh2166** [comment]
Pass at this here: https://github.com/sul-dlss/quimby/blob/loadDataReorder/lib/tasks/load_data.rake Uncertain if we want to add the dependencies to each task though - it makes it super explicit, but also means you can't run just one task if needed. Also, puppet endpoint is consistently timing out on me, so I had to test with a sample / local puppetdb instance.
