### ISSUE TITLE
Use bundler-audit gem for ruby gem security reporting?

### ISSUE THREAD

**Issue by eefahy** [sul-dlss/quimby#69]
- Provides a utility to run on repo gemfiles: https://github.com/rubysec/bundler-audit
- Gemnasium doesn't provide a REST API to query security concerns
- we currently embed the check during deployment via the `dlss-capistrano`
- most of the time a security vulnerability is discovered when attempting to deploy

**Comment by cbeer** [comment]
> Gemnasium doesn't provide a REST API to query security concerns

Does this work for that?
http://docs.gemnasium.apiary.io/#reference/dependency-alerts/projectsslugalerts/get

**Comment by jonrober** [comment]
We're currently querying on sulreports using that API, downloading every project in gemnasium and then finding open alerts for them: https://github.com/sul-dlss/systems-dashboard/blob/master/lib/tasks/download/gemnasium.rake

The only problem is that the REST interface is prone to occasional SSL errors which I've patched some against but still trigger sometimes.  This can be an opportunity to kill off those other error cases.

The way the UI works on sulreports is that we just expose a column for how many open vulnerabiltiies the repo has in gemnasium, and that number links to the gemnasium alerts page.  The gemnasium page has more details than the REST interface provides, so it's better to toss people to it than try and replicate in-app.  Good to do the same here, with the column showing on the main repository list?

**Comment by jonrober** [comment]
Completed in PR #81
